main:
    params: [input]
    steps:
    - extractPhlPropertyData:
        call: http.post
        args:
            url: 'https://us-east4-musa5090s25-team6.cloudfunctions.net/extract_pwd_parcels'
            auth: 
                type: OIDC
    - preparePhlPropertyData:
        call: http.post
        args:
            url: 'https://us-east4-musa5090s25-team6.cloudfunctions.net/prepare_pwd_parcels'
            auth:
                type: OIDC
    - loadPhlPropertyData:
        call: http.get
        args:
            url: 'https://us-east4-musa5090s25-team6.cloudfunctions.net/load_pwd_parcels'
            query:
                sql: 'data_lake/phl_opa_assessments.sql'
            auth:
                type: OIDC