main:
    params: [input]
    steps:
    - prepareModelTrainingData:
        call: http.post
        args:
            url: 'https://us-east4-musa5090s25-team6.cloudfunctions.net/prepare_model_training_data'
            auth: 
                type: OIDC
    - RunModels:
        call: http.post
        args:
          url: https://us-central1-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/musa5090s25-team6/jobs/run-model:run
          auth:
            type: OAuth2
          headers:
            Content-Type: application/json
          body:
            overrides:
              containerOverrides:
                - name: run-model
                  args: []
            taskCount: 1
    - CurrentYearTax:
        call: http.post
        args:
            url: 'https://us-east4-musa5090s25-team6.cloudfunctions.net/run_current_year_tax_sql'
            auth: 
                type: OIDC
    - PastYearTax:
        call: http.post
        args:
            url: 'https://us-east4-musa5090s25-team6.cloudfunctions.net/run_previous_year_tax_sql'
            auth: 
                type: OIDC
    - generateAssessmentChartConfigs:
        call: http.post
        args:
            url: 'https://us-central1-musa5090s25-team6.cloudfunctions.net/generate-assessment-chart-configs'
            auth: 
                type: OIDC
            