main:
    params: [input]
    steps:
    - extractPhlPropertyData:
        call: http.post
        args:
            url: 'https://us-east4-musa5090s25-team6.cloudfunctions.net/extract_phl_opa_properties'
            auth: 
                type: OIDC
    - preparePhlPropertyData:
        call: http.post
        args:
            url: 'https://us-east4-musa5090s25-team6.cloudfunctions.net/prepare_phl_opa_properties'
            auth:
                type: OIDC
    - loadPhlPropertyData:
        call: http.get
        args:
            url: 'https://us-east4-musa5090s25-team6.cloudfunctions.net/load_phl_opa_properties'
            query:
                sql: 'data_lake/phl_opa_properties.sql'
            auth:
                type: OIDC